### ISSUE TITLE
Using gcc-ia16 for ELKS

### ISSUE THREAD

**Issue by mfld-fr** [tkchia/gcc-ia16#1]
Hello, I am MFLD, currently working on [ELKS](https://github.com/jbruchon/elks) to port it to a 8086-based SBC. With the maintainers, we are considering switching from the obsolete BCC to gcc-ia16, and it is nice to see that this fork is alive, and moreover you started to implement far pointers: thank you for this feature that would help a lot.

As your fork is currently moving fast, could you please point out the latest "stable" version in your history, so that we could base our work on it ?

**Comment by tkchia** [comment]
Hello MFLD,

> As your fork is currently moving fast, could you please point out the latest "stable" version in your history, so that we could base our work on it ?

Thank you for your interest!  If you ask me, I would say that my commit [`049677d441`](https://github.com/tkchia/gcc-ia16/commit/049677d4411a7d54e172e57d7a20d30f73b8af94) can be considered the latest "stable" version, since it is the most recent version on my development branch that has undergone GCC's C language regression tests.

I would advise using the [`build-ia16`](https://github.com/tkchia/build-ia16/) scripts to build `gcc-ia16`   --- `build-ia16` downloads and compiles additional code needed by the whole toolchain, and also passes the correct options to GCC's `configure` script.  It should be fine to use a later version of `build-ia16` to build an earlier version of `gcc-ia16`.  However, _do remember to modify_ `fetch.sh` _to check out the correct_ `gcc-ia16` _commit_. :)

If you encounter any issues along the way, please let me know.  Thank you!

**Comment by mfld-fr** [comment]
No issue for now, it works very well as a C frontend to produce assembly, that is in turn processed by legacy dev86 bintools. Even naked, it already helps a lot by detecting many more problems in the source, and by producing more optimized code. Thanks for the advice !

**Comment by tkchia** [comment]
Hello @mfld-fr ,

You may be interested to know that I have also run my latest commit ([`f264e03449`](https://github.com/tkchia/gcc-ia16/commit/f264e0344921476365f7a4c07a5d8b40af0ff204)) through the C language regression tests, so it can also be considered a "stable" version.

This version fixes several far pointer processing bugs reported by @bartoldeman, which were causing compiler crashes.

There is still one known remaining bug (#3) which I will need more time to look into.  In the meantime, the bug is hopefully not too serious, and it is possible to work around it.

Thank you!

**Comment by mfld-fr** [comment]
Hello @tkchia. Yeah, of course we will take your latest "stable" version. Thank you for the update !

**Comment by tkchia** [comment]
Hello @mfld-fr ,

For your information, I have just tested my latest commit [`3c79fd7bc3`](https://github.com/tkchia/gcc-ia16/commit/3c79fd7bc3d5a834491714fb0082a0f985e6ba83) of `gcc-ia16` with GCC's C regression tests, so this can be considered another "stable" version.

Thank you!

**Comment by mfld-fr** [comment]
Hello @tkchia, thank you for the update. Mmm... to save your time and automatically notify us (because I am now watching your fork), what do you think to make some special commits after a non-regression testing, or to put a tag ? That way we would obviously see that a new "stable" version is available ?

**Comment by mfld-fr** [comment]
Forget my latest comment (except the thanks), you already did the tagging. Up to me to be more attentive :smile:.
