### ISSUE TITLE
Verify if -mcmodel=medium still enables -msegment-relocation-stuff

### ISSUE THREAD

**Issue by asiekierka** [tkchia/gcc-ia16#114]
Seems to have regressed sometime after https://github.com/tkchia/gcc-ia16/commit/9336aa4050e418ea80e86c60e874957132decaf5 in my testing; building libgcc with `-mcmodel=medium` and the other flags I use in Wonderful worked on that commit, but latest HEAD requires adding `-msegment-relocation-stuff` manually.

EDIT: (If it is no longer meant to be manually enabled, the comment in `ia16.opt` might need an update.)

**Comment by tkchia** [comment]
Hello @asiekierka,

`-mcmodel=medium` should indeed enable `-msegment-relocation-stuff` automatically &mdash; unless you are using `-mdosx`, which you are not.

I probably need to look into what is going on.  Perhaps for now you can try passing a `-v` option as well to `ia16-elf-gcc`, to more clearly see what the front-end driver is doing.

Thank you!

**Comment by asiekierka** [comment]
>unless you are using -mdosx

That *might* be it, as it seems that even though I disable multilib, libgcc insists on being built in a multilib way, and as such passes a variety of flags, including `-mdosx`. I don't think this was the behaviour on older versions, but I don't see what could possibly have changed it...

Sorry for bothering you again!

**Comment by tkchia** [comment]
Hello @asiekierka,

I am not sure the multilib `libgcc` build explains it &mdash; the multilib settings I use explicitly exclude `-mdosx -mcmodel=medium` (since it is simply not supported yet).

Again, maybe try looking at the output of `-v` from `ia16-elf-gcc` &mdash; e.g. to see what specs files the front-end is using and what options it is passing to the compiler passes.  If it is the `libgcc` build that causes problems, try adding the `-v` inside `libgcc/config/ia16/t-ia16`.

Thank you!

**Comment by asiekierka** [comment]
I'm an idiot. I forgot a `\` in my buildscript.
