### ISSUE TITLE
how DPMI-safe is libc?

### ISSUE THREAD

**Issue by stsp** [tkchia/gcc-ia16#123]
Hi.

IIRC in Borland C (even if it was ~30
years ago) I could switch to PM with
DPMI and keep using most of anything
from libc. But with ia16 libc only _dos_xxx()
APIs work correctly in prot mode.
The rest crashes. DPMI host supports
DOS API translation.
I suppose libc plays with segment registers
even within the small memory model?

**Comment by tkchia** [comment]
Hello @stsp,

There is a `-mdosx` compiler option.  Thank you!

**Comment by stsp** [comment]
Yes but I need a mixed-mode executable
with custom PM/RM switchings.
Its not like I am asking to implement something
for me. Its rather that this is usually supported
quite naturally. So what prevents this from
working here?

**Comment by stsp** [comment]
Also -mdosx is 16bits only AFAIK,
otherwise I'd use it.

**Comment by tkchia** [comment]
Hello @stsp,

> Its rather that this is usually supported quite naturally.

Nothing is "just" supported naturally.  The assumption is actually a bit insulting, in my opinion.  If something works &mdash; e.g. in Borland's DOS extender &mdash; it is because someone took the trouble to make sure it works, e.g. through stress testing.

> So what prevents this from working here?

A few things, at least:
* `gcc-ia16` is more aggressive in its use of segment registers in real mode, e.g. `%ds` can be used to hold temporary operands that are not segment values.
* You may be encountering the use of some MS-DOS functions that are not "translated" by the DOS extender.  In particular `newlib-ia16` may need to go through DPMI to invoke MS-DOS's DBCS functionality, to figure out which byte values may start double-byte characters.  DBCS support is needed to correctly parse file paths.
* Some things (e.g. `int 0x13`) are simply not directly supported.

Thank you!

**Comment by stsp** [comment]
Sorry, I didn't mean it should be
"naturally supported by you". :)
I rather meant that DPMI creates
an environment where the small-model
realmode prog can still execute mostly
fine. So if it isn't, then the question.
I of course do not mean _everything_,
like int13 and other things you mentioned.
But why `printf()` breaks?
I believe the only reason for it to break,
is that, in fact, you use %ds for temporaries?

**Comment by stsp** [comment]
`puts()` breaks, I mean - everything.
`_dos_write()` is fine.

**Comment by stsp** [comment]
```
static unsigned short psp_sel;

static void _puts(const char *str)
{
    _dos_write(STDOUT_FILENO, str, strlen(str), NULL);
}

static void dpmi_switch(void)
{   
    union REGPACK r = {};
    void __far (*sw)(void);
    unsigned mseg, f;
    int err;

#define CF 1
    r.w.ax = 0x1687;
    intr(0x2f, &r);
    if ((r.w.flags & CF) || r.w.ax != 0) {
        fprintf(stderr, "DPMI unavailable\n");
        exit(EXIT_FAILURE);
    }
    if (!(r.w.bx & 1)) {
        fprintf(stderr, "DPMI-32 unavailable\n");
        exit(EXIT_FAILURE);
    }
    sw = MK_FP(r.w.es, r.w.di);
    err = _dos_allocmem(r.w.si, &mseg);
    if (err) {
        fprintf(stderr, "malloc of %i para failed\n", r.w.si);
        exit(EXIT_FAILURE);
    }
    asm volatile(
        "mov %3, %%es\n"
        "lcall *%4\n"
        "pushf\n"
        "pop %0\n"
        "mov %%es, %1\n"
        "push %%ds\n"
        "pop %%es\n"
        : "=r"(f), "=r"(psp_sel)
        : "a"(1), "r"(mseg), "m"(sw)
        : "cc", "memory");
    if (f & CF) {
        fprintf(stderr, "DPMI init failed\n");
        exit(EXIT_FAILURE);
    }
    _puts("DPMI ok\n");
}
```

Just in case you want to see it for
yourself w/o writing an example.

**Comment by tkchia** [comment]
Hello @stsp,

This mode of using the C library is simply not supported.  In fact I am not sure if classical toolchains such as Watcom C are even supposed to support such use.

(Anyway, I also tried your above code under Open Watcom (with the `asm` part suitably translated of course).  The `"DPMI ok"` part ran fine, but the code later crashed in `__GETDS` &#x219c; `__FiniRtns`, while the program was trying to exit.)

![image](https://user-images.githubusercontent.com/5507843/204367523-fa32eddf-188e-4bcc-aa20-758c42967200.png)

Thank you!

**Comment by stsp** [comment]
Yeah, `exit()`, as many other things,
do not work. DPMI app should terminate
specially.
But I wonder what "simply not supported"
mean here. The example above works
with ia16-gcc, but replace `_puts()` with
`puts()` and it breaks. Any reason how
exactly it is not supported? :)
I am intentionally not asking "why" - that's
because you do not have enough time to
get it supported. But how and in what way
it became unsupported?

**Comment by stsp** [comment]
Lets put it very explicitly: why `puts()`
breaks? :)

**Comment by stsp** [comment]
`mov ds, ax` on your screen - is this
where %ds is used for temporaries?

**Comment by stsp** [comment]
You are right, `exit()` is a valid case
too. So I suppose you meant to show
me this `mov ds, ax`?

**Comment by tkchia** [comment]
Hello @stsp,

> But how and in what way it became unsupported?

It was never supposed to not break &mdash; simple as that.  The `libc` &mdash; whether for `gcc-ia16` or for Open Watcom &mdash; assumes that it is operating in real mode, because it is started in real mode.  If you break that assumption, then you get to keep the pieces.

If you decide to switch to protected mode halfway, then the `libc` as a whole is not aware that you have switched to protected mode.  All the internal code and data structures are set up to work in real mode, and to assume that `libc` is (still) operating in real mode.  This is also the same reason that `exit` (along with `atexit` handlers and whatnot) suddenly crashes in Open Watcom.

> `mov ds, ax` on your screen - is this where %ds is used for temporaries?

This was actually from a run of the _Open Watcom_ compiled version of your program.  The crash happened inside Watcom's internal `__GETDS` function.

Thank you!

**Comment by stsp** [comment]
> If you break that assumption, then you get to keep the pieces.

But can we get more technical on that? :)
I only wonder how exactly it breaks.
All data structures are still perfectly
accessible because PM DS maps
RM DS, and my code explicitly restores
ES.
Is the use of %ds for temporaries the one
and only reason of all problems?

**Comment by tkchia** [comment]
Hello @stsp,

Read what I mentioned about the Open Watcom code.  The screenshot is from a run of the Open Watcom version.  Thank you!

**Comment by stsp** [comment]
Well, watcom does something with DS.
But my question is not about Watcom.
My question is about ia16-gcc.
If you know why it breaks, why not to
tell? :) If you don't - why it is not interesting
to find out?

**Comment by stsp** [comment]
Please note that I explicitly mentioned
small model. Were you testing small
model? It shouldn't play with segregs
too much.

**Comment by tkchia** [comment]
Hello @stsp,

> If you know why it breaks, why not to
> tell? :) If you don't - why it is not interesting
> to find out?

Because it does not need to not break.

What you do was never guaranteed to work even in the past.  There is no reason why it suddenly needs to work now.

So yes, I am not interested to find out why this thing that never worked in the past, and that was never supposed to work in the past, is now (still) not working.  (Especially since there is a lot of other more useful stuff I could be doing.)

If you want to do something weird, the burden is on _you_ to find a way that works.  Good luck.

Thank you!

**Comment by stsp** [comment]
> If you want to do something weird, the burden is on you to find a way that works. Good luck.

OK, since dos.h API works, I'll manage.
It appears it puts %es to various addresses,
not sure why. If I trap that in DPMI and
allocate a descriptor to map that addr, then
things start to work, eg puts() works, exit()
works. Some funcs are still crashing because
%es ends up with 0, which is not trapped.
Anyway, I suppose it is really using %es
as a temporary, because the values I see,
make no sense to me.

**Comment by stsp** [comment]
> There is a -mdosx compiler option. Thank you!

OK I ended up with that solution
actually. :) It appears that -mdosx
produces a very well-behaved code
that doesn't seem to play with segregs.
I managed to map the code and data
segments into a 32bit DPMI client, and
now I can use libi86 from 32bit dpmi.
And AFAICT its stable.
Its even a much more powerful approach
than to map the real-mode prog into
dpmi, so I think I should stick to that one.

There is just one draw-back here: such
approach is not very portable. It only
works so far on dosemu2 with this hack:
https://github.com/dosemu2/dosemu2/pull/1826
Not sure how that can/should be solved.
