### ISSUE TITLE
long type seems broken

### ISSUE THREAD

**Issue by stsp** [tkchia/gcc-ia16#124]
```
#include <stdio.h>

static volatile int hi = 2;
static volatile int lo = 0xc000;

static long foo(void)
{
    return (((long)hi << 16) | lo);
}

int main(void)
{
    long l = foo();
    printf("val=%lx\n", l);
    return 0;
}
```

This gives `ffffc000` with ia16-gcc
and `2c000` (correct) on host gcc.

**Comment by ghaerr** [comment]
Hello @stsp,

This isn't an error, but rather a result of sizeof(int) being 16 on ia16-elf-gcc, but 32 on host gcc. In the expression `((long)hi << 16) | lo`, since `hi` is cast as long, `lo` must also be converted from int to long. Since `int` is signed 16-bits on ia16-elf-gcc, it is signed-extended from 0xc000 to 0xffffc000.

Thank you!

**Comment by stsp** [comment]
Thanks!
Making hi/lo unsigned seems to work.
