### ISSUE TITLE
support for int86 C function

### ISSUE THREAD

**Issue by toncho11** [tkchia/gcc-ia16#141]
Can the int86 function be added?

I would like to use it in this code (on ELKS):

```
void set_vga_mode(byte mode)
{
  union REGS regs;

  regs.h.ah = SET_MODE;
  regs.h.al = mode;
  int86(VIDEO_INT, &regs, &regs);
}
```

**Comment by asiekierka** [comment]
`libi86`, which is a part of the full `build-ia16` toolchain, already has the `int86` function implemented.

**Comment by tkchia** [comment]
Hello @toncho11, hello @asiekierka,

Indeed.  `int86( )` should also work on the ELKS platform.

Then again I am not sure if it is a good idea to rely on IBM BIOS functionality (e.g. `int 0x10`) under ELKS.  It is possible that your ELKS program will be run on a machine which may be x86-16 but may not be IBM-compatible.

Thank you!

**Comment by tkchia** [comment]
Hello @toncho11,

For targeting ELKS, you should probably consider using @ghaerr's Nano-X API instead (http://microwindows.org/).  Thank you!

**Comment by toncho11** [comment]
Nano-X is too big for drawing a single VGA line.
So the function should be in int86.h?
What is libi86?

**Comment by ghaerr** [comment]
Hello @toncho11, hello @tkchia,

> Can the int86 function be added?
> I would like to use it in this code (on ELKS):

> Then again I am not sure if it is a good idea to rely on IBM BIOS functionality (e.g. int 0x10) under ELKS. 

I would say that, in general, calling BIOS functions from ELKS applications programs is unsafe. The reason is that any running ELKS application may be interrupted by the hardware timer interrupt, and the kernel may, if the process has run out of its time slice, switch stacks to another runnable application (the `/bin/init` program may be running auto-sync, for example). After that, the other program may make an ELKS system call to perform BIOS disk I/O, in which case the BIOS will have found itself being reentered. I'm not confident that all (or any?) BIOSes are reentrant - which if not could then corrupt the system by having multiple BIOS calls semi-completed saved in the ELKS per-process kernel stacks.

@tkchia would probably know more than I as to whether a given set of BIOS `int` calls are allowed to be "stacked", but in general the BIOS design works only for DOS-style programs that aren't time sliced. (Does DOS ever call the BIOS or does IO.SYS completely take over those functions in all DOS versions)?

> you should probably consider using @ghaerr's Nano-X API instead

If Nano-X is too big, feel free to pull out some of its lower-level EGA driver draw routines that just write to the EGA hardware without calling the BIOS. I can help you with that if you want to take a first cut at some low level draw functions.

Thank you!

**Comment by toncho11** [comment]
@ghaerr 

I just wanted to follow this tutorial: http://www.brackeen.com/vga/shapes.html
There is only one interrupt call to set up the VGA mode and then draw a line. How do you set the screen mode in Nano X in the correct way for ELKS?

**Comment by ghaerr** [comment]
Hello @toncho11,

> There is only one interrupt call to set up the VGA mode and then draw a line. How do you set the screen mode in Nano X in the correct way for ELKS?

Well - you've got me on this one: Nano-X on ELKS can either use a single BIOS call, or initialize the EGA itself. A look at the actual source in elkscmd/nano-X/drivers/scr_bios.c shows that it's actually configured to use a BIOS INT 10h call, the very thing I just said is in general unsafe!

To talk more about how this all works, we should probably open a discussion at ELKS. In the meantime, reading scr_bios.c and elkscmd/nano-X/drivers/vgaplan4.c may help to show the lower level of the work required to actually draw a pixel on a 16-color EGA or VGA display.

Thank you!
