### ISSUE TITLE
[question] -mcmodel=small or -mseparate-code-segment ?

### ISSUE THREAD

**Issue by mfld-fr** [tkchia/gcc-ia16#23]
Hello @tkchia,

I am reworking some Makefiles using `ia16-elf-gcc`, and I wonder why the previous contributor used the `-mseparate-code-segment` in place of `-mcmodel=small`. Could you please briefly explain what is the difference between the two options ?

**Comment by tkchia** [comment]
Hello @mfld-fr ,

Currently `-mseparate-code-segment` only disables compiler features that assume a single address space.  Specifically, it blocks the use of trampolines for implementing [nested functions](https://gcc.gnu.org/onlinedocs/gcc/Nested-Functions.html).  It does not otherwise affect code generation.

`-mcmodel=small` in addition also _enables_ a bunch of other features to better support the small memory model (and more):
  * It turns on support for MS-DOS `.exe` (`MZ`) relocations, so you can e.g. create initialized static far pointers.
  * It also enables static variables which are themselves `__far` (these are placed outside both `.text` and `.data`).
  * It makes `ia16-elf-ld` use a different linker script which lays out an `.exe` header and relocation entries.

I guess this arrangement can use some improvement though --- perhaps `-mseparate-code-segment` and `-mcmodel=small` can be unified to mean the same thing (if that is a good idea), or the handling of relocations can be made less MS-DOS-centric.

Thank you!

**Comment by mfld-fr** [comment]
Thank you for your response.

AFAIK, a MZ executable is loaded as one piece into a contiguous memory. In ELKS project, we split the executable into a separated code segment and a data + stack segment. This is useful to keep the code in ROM to save memory, or to share that code segment between processes. So I guess `-mseparate-code-segment` is the right option for us (in term of semantic).

Indeed we are still working in the small model (CS != DS == SS), and so the `-mcmodel=small` option looks confusing, as you explain it triggers features to support actually the large model through segment relocation and using far pointers to address memory 'inside' program segments.

In our case, we are using the `a.out` format (we plan to move to ELF later) and we intend to use the far pointers only to address memory 'outside' the program segments.

Could I then suggest to trigger the MZ format specifics with another option than the one related to the memory model, and add the large memory model option to trigger the 'inside' far pointer capabilities, not needed in the small model ?

**Comment by tkchia** [comment]
Hello @mfld-fr ,

Thanks for the feedback!

Well, yes, as I said, the current arrangement can most probably use some improvement.

> as you explain it triggers features to support actually the large model through segment relocation and using far pointers to address memory inside program segments.

On MS-DOS, one generally _needs_ to use the `MZ` format --- though not necessarily with relocations --- just to properly express programs with more than 64 KiB of text + initialized data.<sup>(*)</sup>

<sup>(*) I know that `bcc`, the original ELKS compiler, also supports a "separate I&amp;D output" mode --- which means 64 KiB + 64 KiB == 128 KiB at runtime.  Unfortunately, it uses the headerless `.com` format rather than `MZ`, so a program cannot have a total _initialized_ ⟨ text + data ⟩ size of more than 64 KiB, and that is a bit limiting.  `gcc-ia16` avoids this limitation by always using the `MZ` format whenever the small model is used.</sup>

Other than that, I agree that the support for relocations (while possibly useful) is not really essential for the proper working of the small memory model.

So perhaps a semi-workable arrangement will be this:

  * Unify `-mseparate-code-segment` and `-mcmodel=small`, so that either option will disable code trampolines _and_ --- if using the Newlib linker script --- trigger the use of the `MZ` format.
  * Maybe create a separate option, say, `-mmz-relocs` (and/or `-mno-mz-relocs`), to control support for stuff which need relocations to work.

Meantime I also hope to figure out how (and if) I should modify `gcc-ia16` to better support ELKS `a.out` and other executable formats such as Windows `NE`...

Do let me know what you think. :-)

> In ELKS project, we split the executable into a separated code segment and a data + stack segment. This is useful to keep the code in ROM to save memory, or to share that code segment between processes.

I think this is also possible under MS-DOS, with some extra code at program startup, though I am not sure whether anyone would really like to use such a thing. :-)

Thank you!

**Comment by mfld-fr** [comment]
> Meantime I also hope to figure out how (and if) I should modify gcc-ia16 to better support ELKS a.out and other executable formats such as Windows NE...

No, I think supporting ELKS `a.out` is not worth, because 1) it is quite old and not the same as Linux one and 2) we would like to move to ELF to be able to use the debug facilities of `gdb` while testing in QEMU.

Until that move, we would like `gcc-ia16` to output ELF, and then convert ELF with a custom tool to ELKS `a.out`. Therefore having `gcc-ia16` to output MZ format with both options is not what we expect.

Edit after discussion closure : thanks to @tkchia advice, we won't use a custom tool but we generate the ELKS `a.out` directly from LD with a custom script.

**Comment by mfld-fr** [comment]
About the BCC capabilities, I don't understand your comment, because I weekly compile the ELKS kernel with it (plus `as86` and `ld86`) with a total size (.text + .data) > 64 KiB in the ELKS `a.out` format.

**Comment by tkchia** [comment]
Hello @mfld-fr ,

> Until that move, we would like gcc-ia16 to output ELF, and then convert ELF with a custom tool to ELKS `a.out`. Therefore having gcc-ia16 to output MZ format with both options is not what we expect.

Well, no need to worry --- for now, you will still need to explicitly specify the output format (as ELF) in any case, so I think changing `-mseparate-code-segment` to output `MZ` files (rather than `.com` files) by default should not affect what you want to do.

In the long run, I hope to add some explicit support for the ELKS OS to the whole toolchain (hopefully, one just needs to tell GCC "hey, this program is for running on ELKS", and it will do the necessary things under the hood to support that, like choosing the appropriate Newlib libraries and linker flags).  I will see if I can start adding some experimental support now.

> 2) we would like to move to ELF to be able to use the debug facilities of gdb while testing in QEMU.

This is interesting.  Do you currently have any samples of such ELF files you are using?  I would like to take a look, to get an idea of what kind of output I should aim for.

> About the BCC capabilities, I don't understand your comment, because I weekly compile the ELKS kernel with it (plus `as86` and `ld86`) with a total size (.text + .data) > 64 KiB in the ELKS `a.out` format.

Sorry I was not clear enough.  I was referring to `bcc`'s capabilities when compiling to MS-DOS executables (`-Md`) specifically.  In this case, `bcc` will output to the DOS `.com` format, which has the limitation.

Thank you!

**Comment by tkchia** [comment]
Hello @mfld-fr ,

> In the long run, I hope to add some explicit support for the ELKS OS to the whole toolchain ... I will see if I can start adding some experimental support now.

Interestingly... I just found out that Lambertsen and Jenner already included some support in `gcc-ia16` for compiling ELKS binaries (see e.g. `gcc/config/ia16/elks.h`).  It seems to involve building a whole separate toolchain, with a target triple `ia16-*-elks` rather than `ia16-*-elf`.

Having a separate toolchain for each OS does seem to be GCC's standard way of supporting multiple OSes.  I am not sure though if it is a good way in this case...

Thank you!

**Comment by mfld-fr** [comment]
Thank you @tkchia for all these clarifications !

I still don't agree to have by default the MZ format for these 2 options, and having to explicitly specify the ELF format in that case; and I still think the MZ format should be explicitly specified. But that's only a discussion about a possible improvement of the option semantic, not critical in our use case, so...

For the ELKS binaries, I agree with you. The current `ia16-*-elf` toolchain suits our needs, so why having another one ? I think you could wipe out this `ia16-*-elks` stuff to avoid any confusion.

And last but not least, to complete the description of our use case, we won't use the `newlib`, but we would port the current BCC `libc` to GCC and archive this port as the new `libc` for ELKS. Because it looks like to be the shortest path for our current toolchain migration (as discussed internally with @jbruchon and @lithoxs in https://github.com/jbruchon/elks/issues/166).

**Comment by tkchia** [comment]
Hello @mfld-fr ,

I have implemented an experimental `-melks` option for `gcc-ia16`.  Currently this just makes GCC switch to a different linker script (`elks-combined.ld` or `elks-separate.ld` in Newlib --- but this may change).  Also, the input program is not linked to any C library yet.

Thank you!

**Comment by mfld-fr** [comment]
Oh, nice, thank you @tkchia ! Let me try this right now... I suppose I should now put `-mcmodel=small -mno-segment-relocation-stuff -melks` in place of `-mseparate-code-segment` on the GCC command line ?

**Comment by tkchia** [comment]
Hello @mfld-fr ,

Yes. :-)  You can still use `-mseparate-code-segment` instead of `-mcmodel=small` --- both options now do the same thing.

Thank you!

**Comment by mfld-fr** [comment]
Mmm... does your latest commit contain the new LD scripts ?
```
mfld@home /mnt/data/home/mfld/advantech/elks/elks $ ia16-elf-gcc -mcmodel=small -mno-segment-relocation-stuff -melks test.s -o test
ia16-elf-gcc: erreur : unable to locate default linker script « elks-separate.ld » in the library search paths
ia16-elf-gcc: erreur : unable to locate default linker script « elks-separate.ld » in the library search paths
/tmp/ccTpRR2S.o: In function `_start':
(.text+0x2): relocation truncated to fit: R_386_16 against `.data'
collect2: erreur : ld a retourné 1 code d'état d'exécution
```

**Comment by tkchia** [comment]
Hello @mfld-fr ,

The scripts are (and were) part of `newlib-ia16` --- though I suppose it will be good to move them over to `elks-libc` in the near future.  For now you can [download them](https://github.com/tkchia/newlib-ia16/tree/newlib-2_4_0-ia16-tkchia/libgloss/ia16) from my Newlib tree.

Thank you!

**Comment by mfld-fr** [comment]
Thanks for the download link ! I used them as a model to write our own LD scripts (`elks-tiny.ld` and `elks-small.ld`, for better consistency with the option names), and it works well. Still have to debug the result of that 'full GNU' build, but we are in a good shape :smile: .

Thank you again for your support !

**Comment by tkchia** [comment]
Hello @mfld-fr ,

Glad to be of help!

I think I would like to include the building of `elks-libc` in my `build-ia16` scripts some time --- do let me know, when you think `elks-libc` is ready enough for this. :-)  Thank you!
