### ISSUE TITLE
frame pointer use with `-mregparmcall`

### ISSUE THREAD

**Issue by bartoldeman** [tkchia/gcc-ia16#30]
I see the standard prologue (`push %bp; mov %sp,%bp` etc.) /epilogue used with `-fomit-frame-pointer`, even if the function does not actually use `bp`. This is particularly relevant with `-mregparmcall` when the frame is not necessary, although even one-parameter cdecl functions without many local variables can benefit (via `%bx` and `%ss:0x2(%bx)` etc).

**Comment by tkchia** [comment]
Hello @bartoldeman ,

Thanks!  I will see how I can get the frame pointer optimized away correctly in the `-mregparmcall` case.

As for getting the compiler to use `%bx` instead of `%bp`, this does seem somewhat harder to do, but it is also something that I hope to implement.

Thank you!

**Comment by tkchia** [comment]
Hello @bartoldeman ,

I have finally implemented a sort of optimization sub-pass which rewrites functions to access the stack frame using `%bx` rather than `%bp`.

For now though, the rewriting currently only happens in very limited cases --- I want to be really sure that it preserves the output code's correctness.

Thank you!
