### ISSUE TITLE
Wrong comparison to zero with '-Os'

### ISSUE THREAD

**Issue by mfld-fr** [tkchia/gcc-ia16#40]
Hello @tkchia,

I am wondering if GCC-IA16 generates the right code for one routine in the ELKS source.

From https://github.com/jbruchon/elks/blob/master/elkscmd/file_utils/cat.c:
```
static int dumpfile(int fd)
{
	int nred;

	while ((nred = read(fd, readbuf, CAT_BUF_SIZE)) > 0) {
		write(STDOUT_FILENO, readbuf, nred);
	}
	if (nred < 0) return -1;
	return 0;
}
```

Generated code:
```
3615:0000  56                 PUSH    SI
3615:0001  55                 PUSH    BP
3615:0002  89 E5              MOV     BP,SP
3615:0004  B8 00 10           MOV     AX,1000h
3615:0007  50                 PUSH    AX
3615:0008  BE AE 00           MOV     SI,00AEh
3615:000B  56                 PUSH    SI
3615:000C  FF 76 06           PUSH    [BP+6h]
3615:000F  E8 B3 12           CALL    12C5h
3615:0012  83 C4 06           ADD     SP,6h
3615:0015  21 C0              AND     AX,AX
3615:0017  7F 08              JG      0021h
3615:0019  F5                 CMC
3615:001A  19 C0              SBB     AX,AX
3615:001C  89 EC              MOV     SP,BP
3615:001E  5D                 POP     BP
3615:001F  5E                 POP     SI
3615:0020  C3                 RET
3615:0021  50                 PUSH    AX
3615:0022  56                 PUSH    SI
3615:0023  B8 01 00           MOV     AX,0001h
3615:0026  50                 PUSH    AX
3615:0027  E8 A1 12           CALL    12CBh
3615:002A  83 C4 06           ADD     SP,6h
3615:002D  EB D5              JMP     0004h
```
I cannot see any path where the routine could return 0 ?

The source is compiled that way:
```
ia16-elf-gcc -fno-inline -mcmodel=small -mno-segment-relocation-stuff -ffreestanding -mtune=i8086 -Wall -Os  -I/mnt/data/home/mfld/advantech/elks-ia16/include -I/mnt/data/home/mfld/advantech/elks-ia16/libc/include -I/mnt/data/home/mfld/advantech/elks-ia16/elks/include -D__ELKS__ -DELKS_VERSION=\"0.2.0-prei86\" -c -o cat.o cat.c
```

**Comment by mfld-fr** [comment]
Additional information: the problem does not occur if I decrease the optimization level to `-O1` (still fails with `-Os`).

**Comment by tkchia** [comment]
Hello @mfld-fr ,

Yes, there is something wrong with `gcc-ia16`'s handling of the flags.

The `andw %ax, %ax` is basically used to compare `%ax` to 0 and set the flags accordingly.  The back-end uses it as a "shorthand" for `cmpw $0, %ax` when it thinks that is OK --- but unfortunately the shorthand is exactly wrong here.  `andw %ax, %ax` does not set the carry flag in the same way that `cmpw $0, %ax` does, and we need the carry flag to be correct (for the subsequent `sbbw %ax, %ax`).

I will try to push a fix soon.

Thank you!

**Comment by tkchia** [comment]
Hello @mfld-fr ,

Hmm... it turns out that there is also a second bug involved, and the `cmc` and the `sbbw %ax, %ax` are also bogus.  It seems that `gcc-ia16` was trying to mash two incompatible comparisons together: the first was to check whether `%ax > 0`, and the next (if `%ax <= 0`) to check whether `%ax` is zero by means of the carry flag (!!).  A correct (if somewhat inefficient) version of the code would look like this:

```
  ...
  cmpw $0, %ax /* <- */
  jg .L3
  cmpw $1, %ax /* <- */
  cmc
  sbbw %ax, %ax
  ...
```

I think I am close to _really_ fixing the problem, but I think I will need to run the regression tests once through again, to be sure that I have not broken anything.

Thank you!

**Comment by mfld-fr** [comment]
I deleted a previous comment: the test on the return value is still wrong after switching from `-Os` to `-O1`:
```
37A5:0028  21 C0              AND     AX,AX
37A5:002A  7F E1              JG      000Dh
```
JG needs CF to be set, that is not the case with AND. It was working anyway because `read()` never returned -1.

**Comment by mfld-fr** [comment]
Just tested commit 2aa70f8c292e4e67b980d7468a011206130bfd7d (after reverting the "far thunk"): no more error in `cat` with option `-Os`. Now waiting for your non-regression testing before closing that issue... Thank you for the fix !

**Comment by tkchia** [comment]
Hello @mfld-fr ,

Thanks!

After sleeping on the problem a bit, I now think I was wrong about the `andw %ax, %ax`.  It _should_ set the flags the same way as `cmpw $0, %ax` does, at least for the flags we do care about (OF, SF, ZF, CF)  --- mainly because subtracting 0 will never overflow (OF) or need a borrow-over (CF).

If so, then the only bug is the mashing of two separate comparisons, i.e. the missing `cmpw $1, %ax`, and I can revert part of the changes I made to my earlier [commit](https://github.com/tkchia/gcc-ia16/commit/bfd61dc96b244e007efd3d0ca1a79783c50d83d1).

Thank you!

**Comment by mfld-fr** [comment]
Mmm... I agree the `and %ax,%ax; jg` works for the '> 0' test, but it would be more understandable (and as efficient) if you replace the `jg` by a `js`, to tell the "poor debugging guy" we only rely on the SF flag in the comparison.

**Comment by mfld-fr** [comment]
I should also had a little sleep before commenting :smile:... forget my previous one.
