### ISSUE TITLE
How does gcc-ia16 differ from 4.9.x's `-m16` flag?

### ISSUE THREAD

**Issue by lpsantil** [tkchia/gcc-ia16#44]
Excuse my ignorance, but how does differ gcc-ia16 from 4.9.x's `-m16` flag?  Is the point to create more of the supporting libs, language features & memory models a DOS C program expects?  Is the hope to support the FD Kernel better than OW?

**Comment by mfld-fr** [comment]
Just RTFM, IA16 is not IA32:
```
-m16
Generate code for a 16-bit environment.
The -m32 option sets int, long, and pointer types to 32 bits, and generates code that runs on any i386 system.
The -m16 option is the same as -m32, except for that it outputs the .code16gcc assembly directive at the beginning of the assembly output so that the binary can run in 16-bit mode.
```
In other words, even with the `-m16` option, the generated code uses i386 instructions. GCC-IA16 uses i86 / i186 / i286 instructions.

**Comment by tkchia** [comment]
Hello @lpsantil,

Yes --- `gcc -m16` basically produces the same _32-bit_ code that `gcc -m32` does, but the 32-bit output code is meant to run in 16-bit mode (on an i386 or above).  So instead of outputting, say,
```
   0:   55                      push   %ebp
   1:   89 e5                   mov    %esp,%ebp
   3:   8b 45 08                mov    0x8(%ebp),%eax
   6:   5d                      pop    %ebp
   7:   66 d1 f8                sar    %ax
   a:   c3                      ret    
```
`gcc` with `-m16` will produce something like
```
   0:   66 55                   push   %ebp
   2:   66 89 e5                mov    %esp,%ebp
   5:   67 66 8b 45 08          mov    0x8(%ebp),%eax
   a:   66 5d                   pop    %ebp
   c:   d1 f8                   sar    %ax
   e:   66 c3                   retl   
```
So `gcc -m16` is a rather different beast from "true" 16-bit compilers such as Turbo C 2.01, Open Watcom, etc.

Thank you!
