### ISSUE TITLE
Troubles with 32bits

### ISSUE THREAD

**Issue by georgp24** [tkchia/gcc-ia16#55]
Hi tkchia,
I try to convert a 32bit program to ELKS. This sets a bit in two 32bit integers to one for every minute of the hour. This to generate a mask. However, it does not work with ia16-elf-gcc. Here is the code:
```
#include <stdio.h>
unsigned long minutes[2];
static void sminute(int min)
{
    if (min >= 32) {
        minutes[1] |= 1 << (min-32);
    } else { 
        minutes[0] |= 1 << (min);
    }
}
int main() {
    int i;
    for (i=0; i<60 ; i++) {
      sminute(i);
      printf("i:%02d,%08x,%08x\n",i,minutes[0],minutes[1]);
      minutes[0]=0;
      minutes[1]=0;
}
	return 0;
}
```
As you can see, it does not set more than 15 bits. Why does this not work and what do I have to do?

**Comment by tkchia** [comment]
Hello @georgp24,

You need to make sure that the `1` value is of a 32-bit type (`unsigned long`) before shifting it; otherwise you will only be shifting bits within a 16-bit `int`:
```
static void sminute(int min)
{
    if (min >= 32) {
        minutes[1] |= 1UL << (min-32);
    } else { 
        minutes[0] |= 1UL << (min);
    }
}
```
The `"%08x"` formats should also be `"%08lx"`, since the values to print are of `unsigned long` type.

Hope the above helps.  Thank you!

**Comment by georgp24** [comment]
Thank you very much tkchia! My program works now!
